---
- hosts: all
  sudo: yes
  tasks:
    - name: install packages
      apt: name={{ item }} state=present update_cache=true
      with_items:
        - git
        - python-dev
        - postgresql
        - postgresql-contrib
        - python-psycopg2
        - libpq-dev
        - gettext
        - emacs

    - name: configure node v0.12
      shell: curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -

    - name: install nodejs and npm
      apt: name={{ item }} state=present update_cache=true
      with_items:
        - nodejs

    - name: symlink nodejs to node
      file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

    - name: install global npm packages
      npm: name={{ item }} global=yes
      with_items:
        - yuglify
        - less
        - bower

- hosts: all
  sudo: yes
  sudo_user: postgres
  tasks: 
    - name: add postgres db
      postgresql_db: name=opendebates
    - name: add vagrant user to postgres
      postgresql_user: db=opendebates name=vagrant priv=ALL role_attr_flags=CREATEDB,CREATEROLE,SUPERUSER

- hosts: all
  sudo: yes
  sudo_user: root
  tasks: 
    - name: install virtualenv
      pip: name=virtualenv

- hosts: all
  sudo: yes
  sudo_user: vagrant
  vars:
    app_root: /vagrant/
    app_path: /vagrant/opendebates
    ve_path: /vagrant/ve

  tasks: 
    # Install specified python requirements in indicated (virtualenv).
    - name: install dependencies to virtualenv with pip
      pip: requirements={{ app_root }}/requirements.txt virtualenv={{ ve_path }} 

    - name: django syncdb
      django_manage: > 
          command=syncdb 
          app_path={{ app_path }}
          virtualenv={{ ve_path }}
          pythonpath={{ ve_path }}/bin/

    - name: django superuser
      django_manage: > 
          command=loaddata 
          app_path={{ app_path }}
          virtualenv={{ ve_path }}
          fixtures={{ app_root }}/opendebates/fixtures/superuser.json
          pythonpath={{ ve_path }}/bin/
